# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7bd9c892ebdb68511e1004ac0b0595ac3666d0ab4c5e4d234b7a0760f792b2176734336368706190fec4fcc702aed9b3a21a0f7246f37b67dd2f448b69a449b

test:
  secret_key_base: 37fe44f995980787d064692a048c26d47d28eafe678a87ba0b354fe4f020f818ac2bb7701bbf1182517591b25d3201916a54b91d496c63b2d8d63481cc34c5ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
